# Changes made to this config file will be overwritten by the application on shutdown
# If you want to change anything, first shutdown the application, adjust the settings and start the application again,
# Any changes made to this config file can have an impact on performance or break the application
# If you want to reset the values to default, delete this file or start the application with the -R argument
Local-Settings:
  Window:
    # If set to false window can no longer be resized
    Window-Resizable: true
    # Default width and height for the application window
    Window-Default-Width: 1280
    Window-Default-Height: 720
  Logging:
    # Setting related to the log messages colors
    Color-Coding:
      # Set if log messages should be color coded
      Enabled: true
      # Log-Level colors
      Colors:
        # DEFAULT: '0xB40000' = Dark Red
        FATAL: '0xB40000'
        # DEFAULT: '0xFF0000' = Light Red
        ERROR: '0xFF0000'
        # DEFAULT: '0xE3A300' = Dark Yellow
        WARN: '0xE3A300'
        # DEFAULT: '0xFFFFFF' = White (Default font color for most terminals)
        INFO: '0xFFFFFF'
        # DEFAULT: '0x075ED9' = Light Blue
        DEBUG: '0x075ED9'
        # DEFAULT: '0xA016F4' = Violet
        VERBOSE: '0xA016F4'
        # DEFAULT: '0x404040' = Dark Gray
        STACKTRACE: '0x404040'
        # Trace color is used for color coding metadata (file name and line number)
        # DEFAULT: '0x009432' = Dark Green
        TRACE: '0x009432'
    # Set how many stack traces are allowed to be cached, before the application starts overwriting the oldest one
    Max-Stack-Traces-Cached: 100
    # higher log levels include everything from lower log levels
    # Log - Levels:
    # 0 --> OFF:        logger turned off
    # 1 --> FATAL:      logger displays only fatal errors
    # 2 --> ERROR:      logger displays normal errors
    # 3 --> WARN:       logger displays warnings
    # 4 --> INFO:       logger displays info (DEFAULT)
    # 5 --> DEBUG:      logger displays debug messages (may impact performance, don't use this except if you know what you are doing)
    # 6 --> VERBOSE:    logger displays verbose messages (may impact performance, don't use this except if you know what you are doing)
    # 7 --> STACKTRACE: logger displays everything that happens internally (may impact performance, don't use this except if you know what you are doing)
    Log-Level: 4
    # Set the maximum depth of stack traces (line count)
    # Setting this to -1 will print all available lines (maximum depth)
    Stack-Trace-Depth: 11
    Log-File:
      # If the application log should be written to a log file
      # Enabling, this can impact performance
      Enabled: false
      # If set to true, all log messages will be written to the log file regardless of the Log-Level above
      # If set to false, only log messages with the above-specified Log-Level will be written to the log file
      Log-Level-All: true
      # Set how many log files are allowed to exist, before the application starts overwriting the oldest one
      # a higher number will take up more disk space, especially if a high log level is set
      # Suggested range 1-10
      Max-Files: 1
  User-Preferences:
    # Default directory to open when selecting files
    # You can change this as you like, but it will also be updated automatically based on the last pick:
    # Example: last picked animation -> /example/directory/example-animation.mp4 will open /example/directory/ the next time you select an animation
    # %user.home% refers to the users home directory
    Default-Selection-Dir: '%user.home%'
    # If the app should display a short form status bar on the main app window
    Display-Status-Bar: false
    # If the animation should automatically start playing after uploading finished
    Auto-Play-After-Upload: true
  Network:
    # Toggles automatic IPv4 check that is performed when changing the cube IPv4
    # If disabled, connection may fail on the next remote update attempt
    Check-IPv4: true
    # Network task related settings
    Tasks:
      # tasks that are executed periodically
      Periodic:
        # Delay between status requests
        Status-Request-Clock:
          # Periodically performed requests to ensure animation-list is up-to-date and reconnection is detected reliably
          # This task runs regardless of user activity
          Passive: 5.0
          # Periodically performed request to ensure status dialog and status bar are up-to-date
          # This task only runs if either of the above-mentioned widgets is active
          Active: 1.0
        # Minimum delay between network packets (Seconds)
        # Increasing this number may help if you're experiencing issues with network connection
        Network-Communication-Clock: 0.01