package com.toxicstoxm.LEDSuite.communication.packet_management;

/**
 * Classes that implement this support serialization and deserialization.
 * @since 1.0.0
 */
public interface Serializable<T, R> {

    /**
     * Create a string which represents this class.
     * The class can be reconstructed from the returned string later using {@link #deserialize(Object)}
     * @return the serialized object as string
     */
    T serialize();

    /**
     * Construct an instance of this class using a string generated from {@link #serialize()}.
     * @param string string generated by {@link #serialize()}
     * @return a new instance of this class, constructed from the provided string
     */
    R deserialize(T string) throws DeserializationException;
}
