package com.toxicstoxm.LEDSuite.communication.packet_management;

/**
 * Classes that implement this support serialization and deserialization.
 * @since 1.0.0
 */
public interface Serializable {

    /**
     * Create a string which represents this class. The class can be reconstructed from the returned string later using {@link #deserialize(String)}
     * @return the serialized object as string
     */
    String serialize();

    /**
     * Construct an instance of this class using a string generated from {@link #serialize()}.
     * @param string string generated by {@link #serialize()}
     * @return a new instance of this class, constructed from the provided string
     */
    Serializable deserialize(String string) throws DeserializationException;
}
