package com.toxicstoxm.LEDSuite.communication.packet_management;

/**
 * Classes that implement this interface support serialization and deserialization.
 * <p>Serialization allows an object to be converted into a string format (typically to be sent over a network or stored),
 * while deserialization reconstructs the object from the serialized string.</p>
 * @since 1.0.0
 */
public interface Serializable<T, R> {
    /**
     * Converts the current object into a string representation.
     * <p>This method should produce a string that fully represents the state of the object,
     * which can later be used to recreate the object using {@link #deserialize(Object)}.</p>
     * @return a string representation of the object
     */
    T serialize();

    /**
     * Reconstructs an instance of the class from a string generated by {@link #serialize()}.
     * <p>This method should reverse the process of serialization, using the provided string to restore the object's state.</p>
     *
     * @param string the string to be deserialized, generated by {@link #serialize()}
     * @return a new instance of this class, constructed from the provided string
     * @throws DeserializationException if the string cannot be deserialized into a valid instance
     */
    R deserialize(T string) throws DeserializationException;
}
