name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Get Dependencies and Build
    runs-on: ubuntu-latest
    container:
      image: ubuntu:25.04   # or docker.io/library/ubuntu:plucky

    permissions:
      contents: read

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install libadwaita dependencies
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y \
            libadwaita-1-dev \
            gettext \
            desktop-file-utils \
            git \
            meson \
            ninja-build \
            python3 \
            python3-pip \
            build-essential \
            libgtk-4-dev \
            libglib2.0-dev

      # Set up JDK
      - name: Set up JDK 25
        uses: actions/setup-java@v3
        with:
          java-version: '25'
          distribution: 'temurin'

      - uses: actions/setup-python@v1

      # Meson Install
      - name: Meson Install
        uses: BSFishy/meson-build@656b2a360964b249ac82905a52018921e01d875b
        with:
          action: install
          setup-options: --prefix /tmp/install
          directory: build
          meson-version: 1.6.0
          ninja-version: 1.11.1.2
