name: CI for LEDSuite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install libadwaita dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libadwaita-1

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Install Gradle
      - name: Set up Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: latest

      # Meson Build Setup
      - name: Meson Setup
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: setup
          directory: build
          setup-options: '--buildtype=debug'
          meson-version: latest
          ninja-version: latest

      # Meson Build with Ninja
      - name: Meson Build
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          options: '--verbose'
          meson-version: latest
          ninja-version: latest

      # Meson Install
      - name: Meson Install
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          directory: build
          meson-version: latest
          ninja-version: latest
