name: CI for LEDSuite

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-24.10

    steps:      
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Install libadwaita dependencies
      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libadwaita-1-dev

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      - uses: actions/setup-python@v1

      # Meson Install
      - name: Meson Install
        uses: BSFishy/meson-build@v1.0.3
        with:
          action: install
          directory: build
          meson-version: 1.6.0
          ninja-version: 1.11.1.2
