name: Update Flatpak Sources

on:
  push:
    branches:
      - main

jobs:
  setup-environment:
    name: Setup Environment
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Set up Java Development Kit (JDK)
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

  generate-flatpak-sources:
    name: Generate Flatpak Sources
    runs-on: ubuntu-24.04
    needs: setup-environment  # Ensures environment setup is completed

    steps:
      # Step 1: Checkout the code (again, if necessary)
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Generate flatpak-sources.json
      - name: Generate flatpak-sources.json
        run: ./gradlew flatpakGradleGenerator

  compare-and-sync:
    name: Compare and Update Flatpak Sources
    runs-on: ubuntu-24.04
    needs: generate-flatpak-sources  # Ensures the sources file is generated

    steps:
      # Step 1: Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Compare flatpak-sources.json and create PR if needed
      - name: Compare and Sync flatpak-sources.json
        id: compare
        run: |
          git fetch origin main
          if ! diff -u <(jq . flatpak-sources.json) <(git show origin/main:flatpak-sources.json) >/dev/null; then
              git config --global user.email "dominik@crafti-servi.com"
              git config --global user.name "ToxicStoxm"
              
              # Create a new branch for the update
              git checkout -b update-flatpak-sources
              
              # Synchronize repository to prevent conflicts
              gh repo sync -b update-flatpak-sources
              
              # Stage and commit changes
              git add flatpak-sources.json
              git commit -m "Update flatpak-sources.json"
              
              # Push changes to the remote repository
              git push --set-upstream origin update-flatpak-sources

              # Create a pull request
              gh pr create -B main -H update-flatpak-sources --title 'Merge update-flatpak-sources into main' --body 'Created by GitHub Action'
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
