name: Update Flatpak Sources

on:
  push:
    branches:
      - main

jobs:
  update-flatpak-sources:
    name: Get dependencies and update flatpak sources
    runs-on: ubuntu-24.04

    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          java-version: '23'
          distribution: 'temurin'

      # Generate flatpak-sources.json
      - name: Generate flatpak-sources.json
        run: |
          ./gradlew flatpakGradleGenerator

      # Compare flatpak-sources.json with the one in the main branch
      - name: Compare flatpak-sources.json and create pull request if necessary
        run: |
          git fetch origin main
          if ! diff -u <(jq . flatpak-sources.json) <(git show origin/main:flatpak-sources.json) >/dev/null; then

              BRANCH='update-flatpak-sources'

              git config --global user.email "dominik@crafti-servi.com"
              git config --global user.name "ToxicStoxm"
              
              # Create a new branch for the PR
              git checkout -b $BRANCH

              git ls-remote --exit-code --heads origin refs/heads/$BRANCH | wc -l
              EXIT_CODE=$?

              if [[ $EXIT_CODE == '0' ]]; then
                gh repo sync -b $BRANCH
              fi
              
              # Commit the changes
              git add flatpak-sources.json
              git commit -m "Update flatpak-sources.json"
              
              # Push the changes
              git push --set-upstream origin $BRANCH

              gh pr create -B main -H $BRANCH --title 'Merge $BRANCH into main' --body 'Created by Github action'
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
